/* * PROJECT: Mechatronics Memory Game
 * SHEET: config.h
 * PURPOSE: Global variable definitions, memory allocation, and game constants.
 * This file ensures all .ino sheets share the same data structures.
 */

#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h> // Ensure standard Arduino types are available

// ================================================================
// GAME STATE STORAGE (RAM)
// ================================================================
// Array sizes are fixed at 50 to balance gameplay depth with SRAM limits.
int gameSequence[50];    // Master sequence generated by the system
int currentLength = 0;   // The difficulty "level" (number of steps in current round)
int playerSequence[50];  // Temporary buffer to store the user's attempt
int playerInputCount = 0; // Index tracker for the player's current input position
int highScore = 0;       // Persistent record for Solo Mode

// --- Challenger Mode Specifics ---
#define CHALLENGER_SEQ_LENGTH 4 // Static difficulty for the PvP "Challenge" phase
int secretSequence[50];         // Stores the pattern created by Player A

// ================================================================
// SCORING (Non-Volatile Persistence)
// ================================================================
// uint8_t is used to save SRAM (1 byte per variable, range 0-255).
// Note: EEPROM addresses in other sheets are spaced by 2 to allow for future 'int' expansion.
uint8_t p1Score = 0;      // Duel Mode: Player 1 lifetime wins
uint8_t p2Score = 0;      // Duel Mode: Player 2 lifetime wins
uint8_t p3Score = 0;      // Duel Mode: Player 3 (Bluetooth) lifetime wins

uint8_t chalP1Score = 0;  // Challenger Mode: Player 1 lifetime wins
uint8_t chalP2Score = 0;  // Challenger Mode: Player 2 lifetime wins

// ================================================================
// TIMING & POWER MANAGEMENT
// ================================================================
// Standard debounce time to filter out mechanical noise from tactile switches.
const unsigned long DEBOUNCE_DELAY = 50; 

unsigned long lastActivityTime = 0; // Timestamp (ms) of the most recent interaction
bool isAsleep = false;               // System state flag for the 2-minute power saver

#endif
